# Set theme
theme: alembic-jekyll-theme


# File includes
include:
  - _pages
  
# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# Site settings
url: 'https://www.davidbrett.im'
baseurl: ''
title: 'David J. Brett'
description: 'Pastor, Chaplain, & Carpenter'
permalink: pretty
logo: "/images/djb-blue.png"
social:
  name: "David J. Brett"
  links:
    - https://www.linkedin.com/in/davbrett/
    - https://leeuniversity.academia.edu/DavidBrett
    - https://www.facebook.com/david.brett.9275


# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
 - title: Home
   url: /
 - title: About
   url: /about/
 - title: Blog
   url: /blog/
 - title: Contact
   url: /contact/
 - title: Search
   url: /search/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and devotions"
    feature_text: |
      Welcome to my blog
    feature_image: "/images/unsplash/tomas-robertson-M_duJG81Kv4-unsplash.jpg"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
      image: "/images/unsplash/fleur-dQf7RZhMOJU-unsplash.jpg" # default social posts image
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
      image: "/images/unsplash/fleur-dQf7RZhMOJU-unsplash.jpg" # default social posts image
